//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRepuestosAuto_BD1_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDeAutomovil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoDeAutomovil()
        {
            this.Parte = new HashSet<Parte>();
        }
    
        public int ID_TipoDeAutomovil { get; set; }
        public string Modelo { get; set; }
        public int Año { get; set; }
        public string Detalle { get; set; }
        public int ID_FabricanteDeAutos { get; set; }
    
        public virtual FabricanteDeAutos FabricanteDeAutos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parte> Parte { get; set; }
    }
}
